spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true

logging:
  level:
    org:
      springframework:
        security: info